name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.0'   # Ajuste para a versão que você usa (ex.: 7.0.x, 9.0.x)

      - name: Publish Blazor WebAssembly
        run: |
          dotnet publish ./blazor-webapp-spa -c Release -o public

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_APP_CARTILHA_MEDICINA }}
          channelId: live
          projectId: app-cartilha-medicina